// Generated by CoffeeScript 1.6.1
(function() {
  var DisplayServer, express;

  express = require('express');

  DisplayServer = (function() {

    function DisplayServer(display, streamqueuer) {
      var _this = this;
      this.display = display;
      this.streamqueuer = streamqueuer;
      this.app = express();
      this.server = require('http').createServer(this.app);
      this.io = require('socket.io').listen(this.server);
      this.io.set('log level', 0);
      this.app.use(express["static"](__dirname + '/public'));
      this.app.use(require('less-middleware')({
        src: __dirname + '/public'
      }));
      this.app.get('/', function(req, res) {
        return res.sendfile(__dirname + ("/public/displays/" + _this.display + "/index.html"));
      });
      this.io.sockets.on('connection', function(socket) {
        return _this.streamqueuer.on('data', function(data) {
          return socket.emit('data', data);
        });
      });
    }

    DisplayServer.prototype.run = function(port) {
      return this.server.listen(port);
    };

    return DisplayServer;

  })();

  exports.DisplayServer = DisplayServer;

}).call(this);
