// Generated by CoffeeScript 1.6.1
(function() {
  var DisplayServer, StreamQueuer, argv, displays, ds, fs, sq;

  fs = require('fs');

  StreamQueuer = require('./StreamQueuer.js').StreamQueuer;

  DisplayServer = require('./DisplayServer.js').DisplayServer;

  displays = fs.readdirSync(__dirname + '/public/displays');

  argv = require('optimist').usage('Usage: $0 -d [display] -p [port]').options({
    d: {
      alias: 'display',
      describe: 'The type of display to generate.',
      required: true
    },
    p: {
      alias: 'port',
      describe: 'The port from which the display is served.',
      "default": 9999
    }
  }).check(function(argv) {
    if (displays.indexOf(argv['d']) < 0) {
      throw "\"" + argv["d"] + "\" not supported for display. Must be one of; " + (displays.join(",")) + ".";
    }
  }).argv;

  sq = new StreamQueuer(process.stdin);

  ds = new DisplayServer(argv['d'], sq);

  ds.run(argv['p']);

  process.stdin.on('data', function(d) {
    return process.stdout.write(d);
  });

}).call(this);
