// Generated by CoffeeScript 1.6.1
(function() {

  process.stdin.resume();

  process.stdin.setEncoding('utf8');

  process.stdin.on('data', function(chunk) {
    return process.stdout.write('data: ' + chunk);
  });

  process.stdin.on('end', function() {
    return process.stdout.write('end');
  });

  process.sleep(10000);

}).call(this);
