// Generated by CoffeeScript 1.6.1
(function() {
  var DisplayServer, StreamQueuer, argv, colors, ds, fs, sq, views;

  fs = require('fs');

  colors = require('colors');

  StreamQueuer = require('./StreamQueuer.js').StreamQueuer;

  DisplayServer = require('./DisplayServer.js').DisplayServer;

  views = fs.readdirSync(__dirname + '/public/views');

  argv = require('optimist').usage('Usage: $0 -v [view] -p [port]').options({
    v: {
      alias: 'view',
      describe: 'The type of view to generate.',
      required: true
    },
    p: {
      alias: 'port',
      describe: 'The port from which the view is served.',
      "default": 9999
    }
  }).check(function(argv) {
    if (views.indexOf(argv['v']) < 0) {
      throw "\"" + argv["v"] + "\" not supported for view. Must be one of; " + (views.join(",")) + ".";
    }
  }).argv;

  sq = new StreamQueuer(process.stdin);

  sq.on('end', function() {
    process.stdout.write("<< EOF\n".green);
    return process.exit(0);
  });

  ds = new DisplayServer(argv['v'], sq);

  ds.run(argv['p']);

  process.stdin.on('data', function(d) {
    return process.stdout.write(d);
  });

}).call(this);
